version: "3.8"

services:
  nginx:
    depends_on:
      - server
      - client
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  client:
    build:
      dockerfile: Dockerfile
      context: ./ui
    volumes:
      - /app/node_modules
      - ./ui:/app
    ports:
      - 3000:3000
    depends_on:
      - server
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
      target: dev-build
    volumes:
      - /loaner/node_modules
      - ./server:/loaner
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: bitnami/postgresql:14-debian-11
    restart: always
    environment:
       POSTGRESQL_USERNAME : root
       POSTGRESQL_PASSWORD : passwords
       POSTGRESQL_DATABASE : test
#    volumes:
#      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#volumes:
#  pgdata: