version: "3"

services:
  nginx:
    depends_on:
    - backend
    - client
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    
  backend:
    build: 
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /loaner/node_modules
      - ./server:/loaner
    depends_on:
      - pg
    restart: unless-stopped
    
  client:
    build:
      dockerfile: Dockerfile
      context: ./ui
    volumes:
      - /app/node_modules
      - ./ui:/app
    
  pg:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USERNAME = root
      - POSTGRES_PASSWORD = passwords
      - POSTGRES_DATABASE = test
    ports:
      - '5432:5432'