name: Slack Notifier Test on Push

on:
  push:

jobs:
  slack-notifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/slackbroadcast
        with:
          BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
          MESSAGE: '{"text":"Hello Slack Test"}'
