name: Slack Notifier Test on Push

on:
  push:

jobs:
  notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notifier
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
          SLACK_USERNAME: loaner-release
          SLACK_ICON: ${{ secrets.SLACK_ICON }}
          SLACK_TITLE: 'New Release! :rocket:' 
          SLACK_MESSAGE: New Loaner release, version number.
          SLACK_FOOTER: loaner analytics
