name: Slack Notifier Test on Push

on:
  push:

jobs:
  slack-notifier:
    runs-on: ubuntu-latest
    steps:
      - uses: acions/checkout@v2
      - uses: .github/actions/slackbroadcast
        env:
          BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
        with:
          MESSAGE: '{text:"Hello Slack Test"}'
